apiVersion: mvela.oam.dev/v1alpha1
kind: Simple
managedCluster: 2
kubeconfigOpts:
  output: /Users/qiaozp/.vela/kubeConfig
HelmOpts:
  version: 1.2.4
registries:
  mirrors:
    docker.io:
      endpoint:
        - "https://hub-mirror.c.163.com"
        - "https://mirror.baidubce.com"
#storage:
  #endpoint: mysql://tcp(user:passwd@host:PORT)/DBNAME
  #cert_file: /path/to/client.crt
  #key_file: /path/to/client.key

# keep the same for reuse one database. Using environment var TOKEN would be better
# token: SECRET
